### PR TITLE
Adds easing.

### PR DESCRIPTION
**Pull request by himedlooff**

### CODE REVIEW

**Comment by Scotchester** [comment]
This is probably not related to the PR, but the standard expandable header now has a bottom border:
screen shot 2014-07-01 at 10 53 10

**Comment by himedlooff** [comment]
Yeah once we update to the new docs it should go away since it won't be inside of an `li` at that point.

**Comment by Scotchester** [comment]
Ah yeah, it's still using the old code_examples. Is there anything holding us back from doing the update?

**Comment by Scotchester** [comment]
Resolved verbally to fix the bug later by updating the docs template.

**Pull request merged**
